'use strict';

// Enums for logs we should sample
var LogSamplingEnums = {
    CAPI_ADD_TO_CART_API_FAILURE: 'CAPI_ADD_TO_CART_API_FAILURE',
    CAPI_ADD_TO_CART_EXCEPTION: 'CAPI_ADD_TO_CART_EXCEPTION',
    CHECKOUT_SET_CONFIG_NO_CONFIG: 'CHECKOUT_SET_CONFIG_NO_CONFIG',
    CHECKOUT_SET_CONFIG_EXCEPTION: 'CHECKOUT_SET_CONFIG_EXCEPTION',
    PINTEREST_CONVERSION_SERVICE_API_FAILURE: 'PINTEREST_CONVERSION_SERVICE_API_FAILURE',
    PINTEREST_CONVERSION_SERVICE_EXCEPTION: 'PINTEREST_CONVERSION_SERVICE_EXCEPTION'
}
Object.freeze(LogSamplingEnums);

module.exports = LogSamplingEnums;